### PR TITLE
Fix exception while adding memory references

### PR DESCRIPTION
**Pull request by nicodex**
Added more checks to avoid exceptions while adding the memory references (the real reason is a missing memory block for the library, but that's another story), and to not always override the primary reference to EXEC (if no longer "Analysis")

### CODE REVIEW

**Comment by lab313ru** [comment]
Have you tested it with more than one binary?)

**Comment by nicodex** [comment]
> Have you tested it with more than one binary?)

Yes, I did. Any regressions that I might have missed?

This PR just makes the function somewhat safer. However, the real problem is the manual offset calculation while creating the memory blocks. In some cases `createFunctionsSegment` immediately returns, because it thinks that the segment already exists (it doesn't, the offset points into other segments). So I changed it to search for the next free memory block that is large enough (see pull request #12).

I stumbled over the issue with the deploded [Ambermoon binaries](https://gitlab.com/ambermoon/research/-/tree/master/data/dh/v101-1993-10-22-german), just try the [AM2_CPU](https://gitlab.com/ambermoon/research/-/raw/master/data/dh/v101-1993-10-22-german/Amberfiles/AM2_CPU) to force an exception in the current release version.

---

While we are at it, many thanks for your Ghidra extension, it's very welcome and useful. For my research project I manually created a complete [Ghidra type archive from the Amiga NDK 3.1](https://ghidra.nicode.net/Ambermoon/amiga_ndk31.gdt) (struct offset verification is still in progress). So I do not need/want the Amiga hunks loader to add any types for me :)

**Comment by lab313ru** [comment]
Could you also PR the mentioned issue fix? It also will be awesome to PR gdt for the NDK. Thank you!)

**Comment by nicodex** [comment]
> Could you also PR the mentioned issue fix?

Done, pull request #12

> It also will be awesome to PR gdt for the NDK. Thank you!

The GDT is not yet finished, and currently I'm not sure how to integrate it nicely into the Amiga Hunk Loader.

**Comment by lab313ru** [comment]
You can attach it here when it will be ready, I'll add the code to use it.

Nico Bendlin <notifications@github.com> 22 февраля 2021 г. 14:21:11 написал:

**Comment by nicodex** [comment]
> You can attach it here when it will be ready, I'll add the code to use it.

I had to fix some issues (used the "Structure.Offsets" from the NDK to check the struct/union sizes). Current version attached (updated, including C prototypes): [amiga_ndk31-clib.zip](https://github.com/lab313ru/ghidra_amiga_ldr/files/6039107/amiga_ndk31-clib.zip)

**Pull request merged**
